ILE-3 Sales Employee Backend
Iced-Linta/il-ems-dropwizard pull request #2
Opened 2024-11-06 14:00 UTC by dana-kainos

2024-11-06 14:55 UTC, lukemKainos requested changes

2024-11-06 14:55 UTC, lukemKainos commented on src/main/java/org/example/controllers/SalesEmployeeController.java
> +    public Response getAllSalesEmployees() {
might be bnetter worded as getSalesEmployees

2024-11-06 14:55 UTC, lukemKainos commented on src/main/java/org/example/controllers/SalesEmployeeController.java
> +    public Response deleteSalesEmployee(final @PathParam("id") Integer id) {
why are we using the full type here

2024-11-06 14:55 UTC, lukemKainos commented on src/main/java/org/example/controllers/SalesEmployeeController.java
> +            final @PathParam("id") Integer id,
again full object type?

2024-11-06 14:55 UTC, lukemKainos commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +    private final int updateIdIndex = 7;
i cant help feel this would be better as an enum?

2024-11-06 14:55 UTC, lukemKainos commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +        Connection c = DatabaseConnector.getConnection();
try-execute connection instead?

2024-11-06 14:55 UTC, lukemKainos commented on src/main/java/org/example/models/SalesEmployee.java
> +    public void setSalesEmployeeId(int salesEmployeeId) {
finalise the params

2024-11-06 14:55 UTC, lukemKainos commented on src/main/java/org/example/models/SalesEmployeeRequest.java
> +    public void setFirstName(String firstName) {
finalise the params

2024-11-06 14:55 UTC, lukemKainos commented on src/main/java/org/example/services/SalesEmployeeService.java
> +    public List<SalesEmployee> getAllSalesEmployees()
dont need All

2024-11-06 14:55 UTC, lukemKainos commented on src/main/resources/db/migration/V2__CreateSalesEmployee.sql
> +    nationalInsuranceNumber CHAR(9),
i do wonder if there is a scenario where NIN can be the same for two employees? Just a thought

2024-11-06 15:24 UTC, dana-kainos commented on src/main/resources/db/migration/V2__CreateSalesEmployee.sql
> +    nationalInsuranceNumber CHAR(9),
my thought was there could be multiple employees with null national insurance numbers if they werent from the uk for example

2024-11-06 16:11 UTC, declanlarkin commented on src/main/java/org/example/controllers/SalesEmployeeController.java
No validation taking place anywhere???

2024-11-06 16:11 UTC, declanlarkin commented on src/main/java/org/example/controllers/SalesEmployeeController.java
> +    }
Could we log exceptions, ditto for other methods. i.e
 ```suggestion
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response getAllSalesEmployees() {
        try {
            return Response.ok().entity(
                    salesEmployeeService.getAllSalesEmployees()
            ).build();
        } catch (SQLException e){
            System.out.println("SQL Exception while trying to list sales employees: " + e);
            return Response.serverError().build();
        }
    }
```

2024-11-06 16:11 UTC, declanlarkin commented on src/main/java/org/example/services/SalesEmployeeService.java
Could we get some unit tests for the service please (if thats been covered!)

2024-11-06 16:11 UTC, declanlarkin commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +                + ",salary =?, bankAccountNumber =?, commissionRate=?, nationalInsuranceNumber=? " +
Could we add more line breaks for readability here please

2024-11-06 16:11 UTC, declanlarkin commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +                    "SELECT * FROM salesEmployees;");
lets use prepared statement here for consistency

2024-11-06 16:11 UTC, declanlarkin commented on src/main/resources/db/migration/V2__CreateSalesEmployee.sql
With different types of employees you **could** consider a generic `employee` table that includes the information that every employee will have (employeeId, firstName, lastName, salary, bankAccountNumber, nationalInsuranceNumber) etc etc along with a departmentId that links to a deparments table which would include different types of employees. Then for your salesEmployee table you would only need the employeeId as a fkey and anything that is unique to a sales employee, same for deliveryEmployee etc.

Rough diagram which might make more sense 
![image](https://github.com/user-attachments/assets/4a6332f8-0b9f-4114-a553-2712006cc684)

2024-11-06 16:11 UTC, declanlarkin commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +        Connection c = DatabaseConnector.getConnection();
not closed

2024-11-06 16:11 UTC, declanlarkin commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +        Connection c = DatabaseConnector.getConnection();
not closed

2024-11-06 16:15 UTC, dana-kainos commented on src/main/java/org/example/services/SalesEmployeeService.java
thankfully haven't started unit tests yet hahaha

2024-11-06 16:21 UTC, dana-kainos commented on src/main/java/org/example/controllers/SalesEmployeeController.java
this is a nice to have by the client, there is a ticket for this to be implemented later along with authentication

2024-11-06 16:31 UTC, dana-kainos commented on src/main/resources/db/migration/V2__CreateSalesEmployee.sql
@CharlotteMKainos @dylanmckk @CForde-Kainos

2024-11-06 16:33 UTC, dana-kainos commented on src/main/java/org/example/controllers/SalesEmployeeController.java
> +    }
will make a ticket to do this for all the files once they're complete, along with the frontend repo! thanks

2024-11-06 16:33 UTC, dana-kainos commented on src/main/java/org/example/controllers/SalesEmployeeController.java
> +    }
@dylanmckk @CharlotteMKainos @CForde-Kainos fyi

2024-11-06 16:35 UTC, dana-kainos commented on src/main/resources/db/migration/V2__CreateSalesEmployee.sql
thank you! 🎉 would there be a column in employee for whether it is a sales employee or delivery employee or how would you check which is which if you're going to list them on a web page? or is this the departments table

2024-11-06 16:43 UTC, dylanmckk approved these changes

2024-11-06 17:53 UTC, declanlarkin commented on src/main/resources/db/migration/V2__CreateSalesEmployee.sql
Yep the departmentId in the employee table would link to the departmentId in departments table and thats how you would know the type of employee they are.

i.e to list all sales employees
```
Select * from employee where departmentId = '2';
``` 

with departments table looking like
```
departmentId            departmentName
________________________________________
1                       delivery
2                       sales
3                       hr
```

2024-11-07 10:10 UTC, lukemKainos approved these changes

2024-11-07 10:10 UTC, merged